# Generated by Django 3.1.4 on 2020-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dazfiles',
            field=models.ManyToManyField(blank=True, to='production.DazFile', verbose_name='daz files'),
        ),
        migrations.AlterField(
            model_name='character',
            name='dazpresets',
            field=models.ManyToManyField(blank=True, to='production.DazPreset', verbose_name='daz presets'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dazfiles',
            field=models.ManyToManyField(blank=True, to='production.DazFile', verbose_name='daz files'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dazpresets',
            field=models.ManyToManyField(blank=True, to='production.DazPreset', verbose_name='daz presets'),
        ),
        migrations.AlterField(
            model_name='project',
            name='artifacts_folder',
            field=models.CharField(blank=True, help_text='Where to store generated files for this project. Default is MEDIA_DIR/slug/', max_length=255, null=True, verbose_name='artifacts folder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='release title'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='presets',
            field=models.ManyToManyField(blank=True, to='production.DazPreset', verbose_name='presets'),
        ),
    ]
